### ISSUE TITLE
i cant save image use it

### ISSUE THREAD

**Issue by wennjie** [capacitor-community/media#1]
To Native ->  MediaPlugin savePhoto 116552656
ERROR MESSAGE:  {"message":"Unable to save image to album","errorMessage":"The operation couldn’t be completed. (Cocoa error -1.)"}
⚡️  [error] - ERROR Error: Uncaught (in promise): Object: {"message":"Unable to save image to album","errorMessage":"The operation couldn’t be completed. (Cocoa error -1.)"}

**Comment by stewwan** [comment]
hey 👋

can you share device model and the file you were trying to save?

**Comment by wennjie** [comment]
hello 👬
this is my codes
`export class SaveImageService {
    public info: any = {}
    public album: any = {}
    public media = new Media();
    constructor(
        public platform: Platform,
        public toast: ToastService

    ) {
        this.getInfo()
        this.getAlbums()
    }
    async getAlbums() {
        this.media
            .getAlbums()
            .then(res => {
                let find = res.albums.find((item) => {
                    return item.name == '冰红茶'
                })
                console.log('find->', find)
                if (!find) {
                    this.media.createAlbum({
                        name: "冰红茶"
                    }).then((res) => {
                        console.log('creacte->', res)
                        this.getAlbums()
                    }, err => {
                        // console.log('creacte->', err)
                        // this.getAlbums()
                    })
                } else {
                    this.album = find
                }

            })
            .catch(console.log);

    }
    async getInfo() {
        this.info = await Device.getInfo();
    }
    save(path?) {
        let album = this.info.platform == "ios" ? this.album.identifier : this.album.name
        console.log(album)
        this.media.savePhoto({
            path: "https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1555257160727&di=4b5f956653e10af900bd645ab202ae5c&imgtype=0&src=http%3A%2F%2Fpic.qjimage.com%2Fchineseview090%2Fhigh%2Ftpgrm-2526.jpg",
            album
        })
    }`

**Comment by wennjie** [comment]
i use ios Simulator  and iphone7 12.3.1

**Comment by wennjie** [comment]
android :
`2019-07-02 12:54:12.007 21013-21300/io.ionic.starter V/Capacitor: callback: -1, pluginId: Console, methodName: log, methodData: {"level":"log","message":"Camera"}
2019-07-02 12:54:12.007 21013-21211/io.ionic.starter I/Capacitor/Plugin/Console: Camera
2019-07-02 12:54:12.008 21013-21300/io.ionic.starter V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 61488677, pluginId: MediaPlugin, methodName: savePhoto
2019-07-02 12:54:12.008 21013-21300/io.ionic.starter V/Capacitor: callback: 61488677, pluginId: MediaPlugin, methodName: savePhoto, methodData: {"path":"https:\/\/timgsa.baidu.com\/timg?image&quality=80&size=b9999_10000&sec=1555257160727&di=4b5f956653e10af900bd645ab202ae5c&imgtype=0&src=http%3A%2F%2Fpic.qjimage.com%2Fchineseview090%2Fhigh%2Ftpgrm-2526.jpg","album":"Camera"}
2019-07-02 12:54:12.008 21013-21211/io.ionic.starter D/DEBUG LOG: SAVE VIDEO TO ALBUM
2019-07-02 12:54:12.009 21013-21211/io.ionic.starter D/DEBUG LOG: HAS PERMISSIONS
2019-07-02 12:54:12.009 21013-21211/io.ionic.starter D/DEBUG LOG: ___SAVE MEDIA TO ALBUM
2019-07-02 12:54:12.012 21013-21013/io.ionic.starter D/InputMethodManager: HSIFW - flag : 0 Pid : 21013
2019-07-02 12:54:12.014 21013-21211/io.ionic.starter E/Capacitor/Plugin: RuntimeException occurred
    java.lang.StringIndexOutOfBoundsException: length=5; index=-1
        at java.lang.String.substring(String.java:1935)
        at io.stewan.capacitor.media.MediaPlugin.copyFile(MediaPlugin.java:212)
        at io.stewan.capacitor.media.MediaPlugin._saveMedia(MediaPlugin.java:189)
        at io.stewan.capacitor.media.MediaPlugin.savePhoto(MediaPlugin.java:128)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$2.run(Bridge.java:456)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)`

**Comment by stewwan** [comment]
did you try only on simulators, or have you tried in real devices as well?

I think simulators wont work in this case because they lack of some functionalities.

**Comment by zakton5** [comment]
@stewwan I am running this on an actual device and I am getting the same error

**Comment by zakton5** [comment]
Here is a workaround. Open `Pods/DevelopmentPods/CapacitorMedia/Plugin.swift` and change
```
let creationRequest = PHAssetChangeRequest.creationRequestForAssetFromImage(atFileURL: URL(string: data)!)
                
 if let collection = targetCollection {
  let addAssetRequest = PHAssetCollectionChangeRequest(for: collection)
  addAssetRequest?.addAssets([creationRequest?.placeholderForCreatedAsset! as Any] as NSArray)
}
```
to this
```
let url = URL(string: data)
let data = try? Data(contentsOf: url!)
if (data != nil) {
  let image = UIImage(data: data!)
  let creationRequest = PHAssetChangeRequest.creationRequestForAsset(from: image!)
                    
  if let collection = targetCollection {
    let addAssetRequest = PHAssetCollectionChangeRequest(for: collection)
    addAssetRequest?.addAssets([creationRequest.placeholderForCreatedAsset! as Any] as NSArray)
  }
} else {
  call.error("Could not convert fileURL into Data");
}
```

**Comment by zakton5** [comment]
Created a pull request to solve this issue. @stewwan please review when you can.

**Comment by stewwan** [comment]
released in 0.0.6
@wennjie feel free to try and close the issue

**Comment by PhilippEnertrag** [comment]
The behavior is unchanged. No image can be saved in an album.
iOS 13.1.2 - iPhone SE

  let albumFetchResult = PHAssetCollection.fetchAssetCollections(withLocalIdentifiers: [albumId!], options: nil)

>>> albumFetchResult does not contain any entries although an album with the specified title exists.

**Comment by zakton5** [comment]
@PhilippEnertrag Does it work if you do not try to save to a specific album?

**Comment by PhilippEnertrag** [comment]
@zakton5: please excuse the confusion :)

I just didn't RTFM

> Disclaimer
> Make sure you pass the correct album parameter according to the platform
