### ISSUE TITLE
java.lang.RuntimeException: Source file not found when saving photo

### ISSUE THREAD

**Issue by ngkung** [capacitor-community/media#5]
Actually, the iOS version is fine. However, the Android got problem. It seems to me I have tested the code few months ago and it worked fine. But suddenly it doesn't work when I trying my device. Any idea?

V/Capacitor: callback: 125287492, pluginId: MediaPlugin, methodName: savePhoto, methodData: {"path":"https:\/\/##MYDOMAIN###\/uploads\/albums\/462\/IMG_9720.JPG","album":"Pictures"}
D/DEBUG LOG: SAVE VIDEO TO ALBUM
    HAS PERMISSIONS
    ___SAVE MEDIA TO ALBUM
E/Capacitor/Plugin: RuntimeException occurred
    java.lang.RuntimeException: Source file not found: /uploads/albums/462/IMG_9720.JPG, error: /uploads/albums/462/IMG_9720.JPG: open failed: ENOENT (No such file or directory)
        at io.stewan.capacitor.media.MediaPlugin.copyFile(MediaPlugin.java:225)
        at io.stewan.capacitor.media.MediaPlugin._saveMedia(MediaPlugin.java:189)
        at io.stewan.capacitor.media.MediaPlugin.savePhoto(MediaPlugin.java:128)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$2.run(Bridge.java:537)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
D/Capacitor: Sending plugin error: {"save":false,"callbackId":"125287492","pluginId":"MediaPlugin","methodName":"savePhoto","success":false,"error":{"message":"RuntimeException occurred"}}

**Comment by stewwan** [comment]
hey @ngkung 
can you check from latest ? 1.0.1
also check out [changelog](https://github.com/capacitor-community/media/blob/master/CHANGELOG.md#breaking-change) for a breaking change on java import

**Comment by Jacobra93** [comment]
This is still happening to me on 1.0.1, and I have the plugin correctly imported on the Android side. This works fine on iOS.

**Comment by luisa-project-lary** [comment]
I'm having the same problem when trying to save a video on android.
